name: Continuous Integration

on:
  push:
    branches:
      - feature/**
      - release
      - hotfix
jobs:
  build_and_pull:
    runs-on: ubuntu-latest
    steps:
      -   name: Checkout
          uses: actions/checkout@v5
      -   name: Build da Aplicação
          run: mvn clean package -DskipTests
      -   name: Execução de teste unitario
          run: mvn test
      -   name: Teste de criação da imagem docker
          run: docker build -t gs-9-collab-learning .